/* definitions of syscalls */
#define INS_PRINTF     0
#define INS_FOPEN      1
#define INS_FCLOSE     2
#define INS_FWRITE     3
#define INS_FREAD      4
#define INS_FPRINTF    5
#define INS_FSEEK      6
#define INS_FTELL      7
#define INS_SNPRINTF   8
#define INS_CLOCK      9
#define INS_FSCANF    10
#define INS_FGETC     11
#define INS_UNGETC    12
#define INS_ATOI      13
#define INS_SRAND     14
#define INS_RAND      15
#define INS_SPRINTF   16
#define INS_SSCANF    17
#define INS_FPUTC     18
#define INS_OPEN      19
#define INS_CLOSE     20
#define INS_READ      21
#define INS_WRITE     22
#define INS_LSEEK     23
#define INS_FSTAT     24
#define INS_STRTOL    25
#define INS_STRTOD    26
